-- ENUM
create type order_status as enum ('PENDING','PAID','CANCELLED','FULFILLED');

-- MENU
create table if not exists public.menu_items (
  id          bigint generated by default as identity primary key,
  name        text not null,
  price       integer not null,       -- in IDR
  category    text,
  image       text not null,
  created_at  timestamp with time zone default now(),
  updated_at  timestamp with time zone default now()
);

-- ORDERS
create table if not exists public.orders (
  id           uuid primary key default gen_random_uuid(),
  order_code   text unique not null default 'ORD-' || to_char(now(),'YYYYMMDD') || '-' || left(gen_random_uuid()::text, 8),
  customer_name  text,
  customer_phone text,
  note           text,
  status         order_status not null default 'PENDING',
  total          integer not null default 0,
  created_at     timestamp with time zone default now(),
  updated_at     timestamp with time zone default now()
);

-- ORDER ITEMS
create table if not exists public.order_items (
  id          bigint generated by default as identity primary key,
  order_id    uuid not null references public.orders(id) on delete cascade,
  menu_item_id bigint not null references public.menu_items(id),
  qty         integer not null check (qty > 0),
  price       integer not null  -- snapshot price
);

-- triggers
create or replace function set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists menu_items_set_updated on public.menu_items;
create trigger menu_items_set_updated before update on public.menu_items
for each row execute procedure set_updated_at();

drop trigger if exists orders_set_updated on public.orders;
create trigger orders_set_updated before update on public.orders
for each row execute procedure set_updated_at();
